# def meal
#   'Dinner'
#   puts 'Dinner'
# end

# p meal

# prints 'Dinner' and then nil?
# first string generated by puts statement in meal method
# nil generated by p statement since last statement
# of meal is puts 'Dinner' which returns nil

# According to answer key, a discrepancy between
# puts and p, is that puts doesn't show nil unlike p.